# Generated by Django 4.0.6 on 2025-02-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.JSONField()),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
