# Generated by Django 4.0.6 on 2025-02-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='insta_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='captionApp.instapost')),
            ],
        ),
    ]
