# Generated by Django 4.0.6 on 2025-02-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captionApp', '0002_instapostimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
