# Generated by Django 4.0.6 on 2025-02-14 16:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captionApp', '0003_alter_instapost_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instapost',
            name='images',
        ),
        migrations.AlterField(
            model_name='instapostimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
